import os
import csv
import json
import logging
from pathlib import Path
from typing import Dict, Any, Optional
from backend.tools.registry import registry
from backend.config import settings

logger = logging.getLogger("AEGIS.FileTools")

def resolve_target_path(filename: str, location: Optional[str] = None) -> Path:
    """Resolves target file path based on user requested directory or default desktop/documents."""
    clean_input = filename.strip()
    p = Path(clean_input)
    
    # If absolute path was passed, respect it
    if p.is_absolute():
        p.parent.mkdir(parents=True, exist_ok=True)
        return p

    clean_name = os.path.basename(clean_input)
    
    if location and location.lower() not in ["", "none"]:
        loc_lower = location.lower()
        if "desktop" in loc_lower:
            base_dir = Path(settings.DESKTOP_DIR)
        elif "download" in loc_lower:
            base_dir = Path(settings.DOWNLOADS_DIR)
        elif "document" in loc_lower:
            base_dir = Path(settings.DOCUMENTS_DIR)
        else:
            base_dir = Path(location)
    else:
        base_dir = Path(settings.DESKTOP_DIR)

    base_dir.mkdir(parents=True, exist_ok=True)
    return base_dir / clean_name

@registry.register(
    name="create_file",
    description="Create an actual file on the computer (supports TXT, MD, PY, JS, TS, HTML, CSS, SQL, JSON, CSV, DOCX, PPTX, XLSX).",
    parameters={
        "type": "object",
        "properties": {
            "filename": {
                "type": "string",
                "description": "Filename with extension (e.g., 'calculator.py', 'notes.docx', 'portfolio.html', 'presentation.pptx', 'data.csv')"
            },
            "content": {
                "type": "string",
                "description": "The full text, code, or structured content to put inside the file"
            },
            "location": {
                "type": "string",
                "description": "Target folder (e.g. 'Desktop', 'Documents', 'Downloads', or custom path). Default is Desktop.",
                "default": "Desktop"
            },
            "overwrite": {
                "type": "boolean",
                "description": "Whether to overwrite if the file already exists.",
                "default": False
            }
        },
        "required": ["filename", "content"]
    },
    permission_level="normal",
    category="filesystem"
)
def create_file(filename: str, content: str, location: Optional[str] = "Desktop", overwrite: bool = False) -> Dict[str, Any]:
    target_path = resolve_target_path(filename, location)
    
    # Overwrite protection check
    if target_path.exists() and not overwrite:
        return {
            "status": "already_exists",
            "filepath": str(target_path),
            "message": f"A file named '{target_path.name}' already exists at {target_path.parent}. Please confirm if you would like me to overwrite it.",
            "verified": False,
            "needs_confirmation": True
        }

    ext = target_path.suffix.lower()

    try:
        if ext == ".docx":
            import docx
            doc = docx.Document()
            doc.add_heading(target_path.stem.replace("_", " ").title(), 0)
            for line in content.split("\n"):
                clean_line = line.strip()
                if clean_line.startswith("# "):
                    doc.add_heading(clean_line[2:], level=1)
                elif clean_line.startswith("## "):
                    doc.add_heading(clean_line[3:], level=2)
                elif clean_line.startswith("### "):
                    doc.add_heading(clean_line[4:], level=3)
                elif clean_line.startswith("- ") or clean_line.startswith("* "):
                    doc.add_paragraph(clean_line[2:], style='List Bullet')
                elif clean_line:
                    doc.add_paragraph(clean_line)
            doc.save(str(target_path))

        elif ext == ".pptx":
            from pptx import Presentation
            prs = Presentation()
            # Title Slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            title = slide.shapes.title
            subtitle = slide.placeholders[1]
            title.text = target_path.stem.replace("_", " ").title()
            subtitle.text = "Generated by AEGIS AI Assistant"

            # Content slides from sections
            bullet_slide_layout = prs.slide_layouts[1]
            sections = content.split("\n\n")
            for sec in sections:
                lines = [l.strip() for l in sec.split("\n") if l.strip()]
                if not lines:
                    continue
                c_slide = prs.slides.add_slide(bullet_slide_layout)
                header = lines[0].lstrip("#").strip()
                c_slide.shapes.title.text = header
                tf = c_slide.placeholders[1].text_frame
                tf.text = lines[1].lstrip("-* ").strip() if len(lines) > 1 else ""
                for bullet in lines[2:]:
                    p = tf.add_paragraph()
                    p.text = bullet.lstrip("-* ").strip()
            prs.save(str(target_path))

        elif ext == ".xlsx":
            import xlsxwriter
            workbook = xlsxwriter.Workbook(str(target_path))
            worksheet = workbook.add_worksheet()
            lines = [l.strip() for l in content.split("\n") if l.strip()]
            for r, line in enumerate(lines):
                cols = [c.strip() for c in (line.split(",") if "," in line else line.split("\t"))]
                for c, val in enumerate(cols):
                    worksheet.write(r, c, val)
            workbook.close()

        elif ext == ".json":
            try:
                parsed_json = json.loads(content)
                with open(target_path, "w", encoding="utf-8") as f:
                    json.dump(parsed_json, f, indent=2)
            except Exception:
                with open(target_path, "w", encoding="utf-8") as f:
                    f.write(content)

        elif ext == ".csv":
            with open(target_path, "w", newline="", encoding="utf-8") as f:
                f.write(content)

        else:
            with open(target_path, "w", encoding="utf-8") as f:
                f.write(content)

        # Verification
        if target_path.exists():
            size = target_path.stat().st_size
            loc_label = location.capitalize() if location else target_path.parent.name
            return {
                "status": "created",
                "filepath": str(target_path),
                "filename": target_path.name,
                "size_bytes": size,
                "message": f"Successfully created {target_path.name} ({size} bytes) on your {loc_label}.",
                "verified": True
            }
        else:
            return {
                "status": "error",
                "message": f"Failed to verify file creation at {target_path}.",
                "verified": False
            }

    except Exception as e:
        logger.error(f"Error creating file {filename}: {e}", exc_info=True)
        return {
            "status": "error",
            "error": str(e),
            "message": f"Error creating file: {str(e)}",
            "verified": False
        }

@registry.register(
    name="read_file",
    description="Read the text content of a file on the computer.",
    parameters={
        "type": "object",
        "properties": {
            "filepath": {
                "type": "string",
                "description": "Path to the file to read"
            }
        },
        "required": ["filepath"]
    },
    permission_level="normal",
    category="filesystem"
)
def read_file(filepath: str) -> Dict[str, Any]:
    path = Path(filepath)
    if not path.exists():
        return {
            "status": "not_found",
            "message": f"File '{filepath}' not found.",
            "verified": False
        }
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read(5000)
        return {
            "status": "read",
            "filepath": str(path),
            "content": content,
            "verified": True
        }
    except Exception as e:
        return {
            "status": "error",
            "error": str(e),
            "verified": False
        }

@registry.register(
    name="open_folder",
    description="Open a folder in Windows File Explorer.",
    parameters={
        "type": "object",
        "properties": {
            "folder_name": {
                "type": "string",
                "description": "Folder to open (e.g. 'Desktop', 'Downloads', 'Documents', or full path)"
            }
        },
        "required": ["folder_name"]
    },
    permission_level="normal",
    category="filesystem"
)
def open_folder(folder_name: str) -> Dict[str, Any]:
    f_lower = folder_name.lower()
    if "desktop" in f_lower:
        p = Path(settings.DESKTOP_DIR)
    elif "download" in f_lower:
        p = Path(settings.DOWNLOADS_DIR)
    elif "document" in f_lower:
        p = Path(settings.DOCUMENTS_DIR)
    else:
        p = Path(folder_name)

    if p.exists():
        os.system(f'explorer "{p}"')
        return {
            "status": "opened",
            "folder": str(p),
            "message": f"Opened {folder_name} in File Explorer.",
            "verified": True
        }
    return {
        "status": "not_found",
        "message": f"Folder {folder_name} does not exist.",
        "verified": False
    }
